hybrid_engineer:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: public  # Changed from 'silver' to 'public' to avoid appending
      threads: 2
      keepalives_idle: 0
